export interface GroupMembersSummary {
  id: string;
  givenName: string;
  familyName: string;
  imageUrl: string;
}

export interface GroupBalanceResponse {
  from: string;
  fromUserId: string;
  to: string;
  toUserId: string;
  amount: number;
}

export interface GroupDetailedResponse {
  id: string;
  name: string;
  imageUrl: string;
  members: GroupMemberDetailedResponse[];
}

export interface GroupMemberDetailedResponse {
  id: string;
  email: string;
  imgUrl: string;
  givenName: string;
  familyName: string;
}

export interface CreateGroupRequest {
  name: string;
  imageUrl: string;
  requestedUsers: CreateGroupRequestRequestedUser[];
}

export interface CreateGroupRequestRequestedUser {
  phoneNumber: string;
  email: string;
  fullName: string;
}

export interface UpdateGroupRequest {
  name: string;
  imageUrl: string;
}

export interface AddMembersRequest {
  requestedUsers: AddMembersRequestedUserRequest[];
}

export interface AddMembersRequestedUserRequest {
  phoneNumber: string;
  email: string;
  fullName: string;
}

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface IGroup {
  id: string;
  name: string;
  coverPhoto: string;
  members: Member[];
  repayments: Repayment[];
  memberCount: number;
  createdAt: string;
  updatedAt: string;
  inviteLink: string;
}

export interface Member {
  id: string;
  givenName: string;
  familyName: string;
  avatar: string;
  email: string;
  registrationStatus: `${RegistrationStatus}`;
  amount: number;
  role: `${Role}`;
}

export enum RegistrationStatus {
  Active = "Active",
  InActive = "InActive",
}

export enum Role {
  Admin = "Admin",
  Member = "Member",
}

export interface Repayment {
  from: string;
  to: string;
  amount: number;
}
